version: "3"

services:

  oqs-wireshark:
    container_name: oqs-wireshark
    image: openquantumsafe/wireshark:latest
    # image: openquantumsafe/wireshark:0.7.1
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - ./save_monitoring:/home

  oqs-httpd:
    container_name: oqs-httpd
    image: openquantumsafe/httpd:latest
    # image: openquantumsafe/httpd:0.9.2
    volumes:
      - shared-volume:/opt/httpd/cacert
    networks:
      net0:
        ipv4_address: 172.18.1.4
    depends_on:
      - oqs-wireshark
    environment:
      # default "kyber768:p384_kyber768"
      DEFAULT_GROUPS: kyber768:p384_kyber768
      # default "dilithium3"
      SIG_ALG: dilithium3

  oqs-curl:
    container_name: oqs-curl
    image: openquantumsafe/curl:latest
    # image: openquantumsafe/curl:0.9.2
    volumes:
      - shared-volume:/cacert_curl
    networks:
      net0:
        ipv4_address: 172.18.1.5
    depends_on:
      - oqs-wireshark
      - oqs-httpd
    tty: true
    environment:
      # default "x25519:x448:kyber512:p256_kyber512:kyber768:p384_kyber768:kyber1024:p521_kyber1024"
      DEFAULT_GROUPS: x25519:x448:kyber512:p256_kyber512:kyber768:p384_kyber768:kyber1024:p521_kyber1024
      # default "dilithium3"
      SIG_ALG: dilithium3

    # repeats the curl command every 10 seconds

    # unsafe (without certificate)
    command: watch -n 10 curl --insecure https://oqs-httpd:4433 --curves kyber768
    # safe (with certificate)
    # command: watch -n 10 curl --cacert /cacert_curl/CA.crt https://oqs-httpd:4433 --curves kyber768

networks:
  net0:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  shared-volume:
