version: "3"

services:

  oqs_wireshark:
    container_name: oqs_wireshark
    image: openquantumsafe/wireshark:0.7.1
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=/tmp

  oqs_httpd:
    container_name: oqs_httpd
    image: openquantumsafe/httpd:0.9.2
    networks:
      net0:
        ipv4_address: 172.18.1.4
    depends_on:
      - oqs_wireshark
    environment:
      # default "kyber768:p384_kyber768"
      - DEFAULT_GROUPS=kyber768:p384_kyber768
      # default "dilithium3"
      - SIG_ALG=dilithium3

  oqs_curl:
    container_name: oqs_curl
    image: openquantumsafe/curl:0.9.2
    networks:
      net0:
        ipv4_address: 172.18.1.5
    depends_on:
      - oqs_wireshark
      - oqs_httpd
    tty: true
    # repeats the curl command every 10 seconds
    command: watch -n 10 curl -k https://oqs_httpd:4433 --curves p384_kyber768

networks:
  net0:
    ipam:
      config:
        - subnet: 172.18.1.0/24
